# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user_logeado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento_logeado', to=settings.AUTH_USER_MODEL)),
                ('user_reconocido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento_reconocido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reconocimiento',
                'managed': True,
            },
        ),
    ]
