# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paieelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumReconocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_reconocimientos', models.IntegerField(default=1)),
            ],
        ),
    ]
