# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idframe', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('atraccion', models.FloatField(blank=True, null=True)),
                ('valencia', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sorpresa', models.FloatField(blank=True, null=True)),
                ('enfado', models.FloatField(blank=True, null=True)),
                ('tristeza', models.FloatField(blank=True, null=True)),
                ('disgusto', models.FloatField(blank=True, null=True)),
                ('miedo', models.FloatField(blank=True, null=True)),
                ('felicidad', models.FloatField(blank=True, null=True)),
                ('atencion', models.FloatField(blank=True, null=True)),
                ('video', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaHora', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Reconocimiento',
                'managed': False,
            },
        ),
    ]
